name: Update dependencies

on: [repository_dispatch]

jobs:
  update-webex-component-adapter-interfaces:
    runs-on: ubuntu-latest
    if: github.event.action == 'update-webex-component-adapter-interfaces'
    steps:
      - name: checkout
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.
      - run: |
          npm install @webex/component-adapter-interfaces --save
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git add .
            git commit -m 'fix(@webex/component-adapter-interfaces): update to new version'
            git push origin master
          fi
